# Generated by Django 3.0.7 on 2020-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isIndian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.URLField(default='http://www.nashikproperty.com/uploads/builder-logo/default-logo.png'),
        ),
    ]
